[Window]
# Automatically filled by configurator.py
left = 0
top = 0
width = 800
height = 600

[MQTT]
# Required for remote control via EasyMQTT
broker = daf54500afe84578ac216036e161efd9.s1.eu.hivemq.cloud
port = 8883
username = YOUR_HIVEMQ_USERNAME
password = YOUR_HIVEMQ_PASSWORD
topic = bot/control
client_id = windows-diagnostics-bot
